### Site Settings ###
title               : CSVANKHEDE
description         : >-
                      I'm Chhaya Vankhede a Machine learning engineer,
                      making machine learning work in real world.
baseurl             : ""                     # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          : csvankhede/csvankhede.github.io     # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
remote_theme        : YoussefRaafatNasry/portfolYOU


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md
  - documentation/partials/**                           # For Documentation Only


### Author Info ###
author:
  name              : Chhaya Vankhede
  image             : Data/IMG-20200501-WA0000-01-02.jpeg
#  behance           : your_username
# dribbble          : your_username
  email             : c.s.vankhede@gmail.com
#  facebook          : your_username
  github            : csvankhede
# gitlab            : your_username
# instagram         : your_username
  kaggle            : csvankhede
  linkedin          : chhaya-vankhede-923a17146/
  medium            : c.s.vankhede
# soundcloud        : your_username
# spotify           : your_username
  stackoverflow     : 5847441
# tumblr            : your_username.tumblr.com
# twitch            : your_username
  twitter           : TheCalmBluesta
# vimeo             : your_username
# youtube           : your_channel_name


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name
  elements:                                             # For Documentation Only
    output: true                                        # For Documentation Only


### Disqus ###
disqus: your-short-name-disqus                          # Your website Shortname on disqus


### Analytics ###
analytics:
  enabled: false                                        # Set true to enable analytics
  google:
    tracking_id: your-google-tracking-id


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:                                              # For Documentation Only
      path: ""                                          # For Documentation Only
      type: "elements"                                  # For Documentation Only
    values:                                             # For Documentation Only
      layout: "element"                                 # For Documentation Only
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false                                   # Set to true to enable disqus comments

### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
